// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";

var input = Fs.readFileSync("input.txt", "ascii");

var letters = input.split("");

function uniqueLetters(a) {
  return Belt_SetString.size(Belt_SetString.fromArray(a)) === a.length;
}

function detectMarker(message, markerLength) {
  var result = 0;
  for(var i = 0 ,i_finish = message.length; i < i_finish; ++i){
    if ((i - markerLength | 0) >= 0 && result === 0) {
      var part = message.slice(i - markerLength | 0, i);
      if (uniqueLetters(part)) {
        result = message.slice(0, i).length;
      }
      
    }
    
  }
  return result;
}

console.log("Part 1:", detectMarker(letters, 4));

console.log("Part 2:", detectMarker(letters, 14));

export {
  input ,
  letters ,
  uniqueLetters ,
  detectMarker ,
}
/* input Not a pure module */
