// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Caml_format from "rescript/lib/es6/caml_format.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

var input = Fs.readFileSync("input.txt", "ascii");

function sum(i, j) {
  return i + j | 0;
}

function sumArray(arr) {
  return arr.reduce(sum, 0);
}

var elfs = Js_string.split("\n\n", input);

var calories = elfs.map(function (elf) {
      var splitted = Js_string.split("\n", elf);
      return splitted.map(function (cal) {
                    if (cal.length > 0) {
                      return Caml_format.int_of_string(cal);
                    } else {
                      return 0;
                    }
                  }).reduce(sum, 0);
    });

console.log("Part 1: ", Caml_splice_call.spliceApply(Math.max, [calories]));

console.log("Part 2: ", calories.sort().slice(-3).reduce(sum, 0));

export {
  input ,
  sum ,
  sumArray ,
  elfs ,
  calories ,
}
/* input Not a pure module */
